castle/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url, include, handler400, handler500
from django.conf import settings
from django.conf.urls.static import static
from . import views
from rentals import urls
from profiles import views as team

urlpatterns = [
    path('cp/', admin.site.urls),
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    url('^$', views.home, name='home'),
    url(r'^backoffice/', include('backoffice.urls')),
    # url('^contacts$', views.contacts, name='contacts'),
    url(r'^rentals/', include('rentals.urls')),
    url(r'^news/',    include('news.urls', namespace="news")),
    # url(r'^404$',views.error_404, name='error_404'),
    url(r'^faq/$', views.faq, name='faq'),
    # path('profile/', include('profiles.urls', namespace="profile")),
    path('account/',  include('account.urls', namespace='account')),
    path('profile/',  include('profiles.urls', namespace='profile')),
    path('accounts/', include('allauth.urls')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    # path('teams/',    include('agents.urls', namespace='teams')),
    # path('additions/', include('additions.urls', namespace='additions')),
    url(r'$send/$', views.send_mail, name="send-mail" ),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('teams/', team.list_agents, name='agents'),
    path('team/<int:id>', team.detail_agent, name='agent'),
    # url(r'^imagefit/', include('imagefit.urls')),

]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'castle.views.handler404'
handler500 = 'castle.views.handler500'

news/urls.py
from django.conf.urls import url 
from . import views
from django.urls import path

app_name = 'news'
urlpatterns = [
	url(r'^$', views.list, name='list'),
	path('detail/<slug:slug>/', views.detail, name='detail'),
	path('tag/<slug:tag_slug>/', views.list, name='post_list_by_tag'), 
	path('cat/<slug:cat_slug>/', views.list, name='list_post_by_category'), 
	path('search/', views.post_search, name='search'),
]

rentals/urls.py
from django.conf.urls import url
from . import views

# urlpatterns = [

# 	url(r'^$', views.rent, name='rent-detail'),
# 	url(r'^list$', views.rent_list, name='rent-list'),
# ]

from django.conf.urls import url
from . import views
from django.urls import path, include
from .views import load_coordinates, rent_detail, property_search, getbyid_property

app_name = 'rentals'
urlpatterns = [

	url(r'^$', views.rent, name='rent-detail'),
	url(r'^list$', views.rent_list, name='rent-list'),
    # url(r'^(?P<id>[\w-]+)/$', rent_detail, name='detail'),
    path('<int:id>/', rent_detail, name='detail'),
    path('search/', property_search, name='property_search'),
    path('getbyid_property/', getbyid_property, name='getbyid_property'),
    # path('ajax_message_submit/', ajax_message_submit, name='ajax_message_submit'),
	path('load_coordinates/', load_coordinates, name='ajax_load_coordinates'),  # <-- this one here

]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



castle/views.py
from django.shortcuts import render
from django.core.mail import BadHeaderError, send_mail
from django.http      import HttpResponse, HttpResponseRedirect
from additions.models import FAQ
from rentals.models   import Properties
from profiles.models  import Team 
from contacts.models  import Emails
from django.contrib.auth.models import User
from django.views.decorators.cache import cache_page
from django.views.decorators.vary  import vary_on_cookie
# from django.templates import RequestContext

@vary_on_cookie
@cache_page(60)
def home(request):
	hauses     = Properties.objects.all()[9:]
	print(hauses)
	teams    = User.objects.filter(is_active=True, is_staff=True)[3:] 
	featured = Properties.objects.filter(featured=True)[10:]
	
	return render(request, 'home/index.html',{
		'hauses':hauses,
		'teams':teams,
		'featured':featured})

@vary_on_cookie
@cache_page(3600)
def contacts(request):
	return render(request, 'contacts/contact.html',{})

@vary_on_cookie
@cache_page(3600)
def faq(request):
	faq = FAQ.objects.filter(is_active=True)
	# faq = FAQ.objects.all()
	return render(request, 'faq/faq.html', {'faq':faq})


def error_404(request):
	return render(request, 'errors/404.html')

def handler404(request, exception):
	return render(request, '404.html', {})

def handler500(request, *args, **kwargs):
	return render(request, '500.html', {})


def send_mail(request):
	subject = request.POST.get('subject','')
	message = request.POST.get('message', '')
	from_email= request.POST.get("from_email","")
	if subject and message and from_email:
		try:
			print('email has been sent successfully')
			send_mail(subject, message, from_email, ['admin@example.com'])
		except:
			return HttpResponse('Invalid header found.')
		return HttpResponseRedirect('/contact/thanks/')
	else:
		return HttpResponse('Make sure all fields are entered and valid.')	

			

templates/castle/home/content.html
{% load static %}
{% load i18n %}
{% load addition_tags %}
<!-- Gallery -->

<!-- <section id="property" class="padding bg_gallery">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <h2 class="uppercase">real estate properties</h2>
        <p class="heading_space">We have Properties in these Areas View a list of Featured Properties.</p>
      </div>
    </div>
    <div class="clearfix">
      <div id="filters-property" class="cbp-l-filters-button text-center">
        <div data-filter=".latest" class="cbp-filter-item-active cbp-filter-item">LATEST</div>
        <div data-filter=".sale" class="cbp-filter-item">SALE</div>        
        <div data-filter=".rent" class="cbp-filter-item">RENT</div>
      </div>
    </div>
    <div id="property-gallery" class="cbp listing1">
      {{objs}}
      {% for obj in objs %}
        <div class="cbp-item latest {% if p.purpose == '0' %}rent{% else %}sale{% endif %}">
          <div class="property_item">
            <div class="image">
              <a href="{{p.get_absolute_url}}"><img src="{% static 'images/listing1.jpg' %}" alt="latest property" class="img-responsive"></a>
              <div class="price clearfix"> 
                <span class="tag pull-right">${{obj.price}} Per Month</span>
              </div>
              <span class="tag_t">{% if p.purpose == '0' %}{% trans "For Rent" %} {% else %}{% trans "For Sale" %}{% endif %}</span> 
              <span class="tag_l">Featured</span>
            </div>
            <div class="proerty_content">
              <div class="proerty_text">
                <h3 class="captlize"><a href="property_detail1.html">Park avenue apartment</a></h3>
                <p>45 Regent Street, London, UK</p>
              </div>
              <div class="property_meta transparent"> 
                <span><i class="icon-select-an-objecto-tool"></i>4800 sq ft</span> 
                <span><i class="icon-bed"></i>2 Office Rooms</span> 
                <span><i class="icon-safety-shower"></i>1 Bathroom</span>   
              </div>
              <div class="property_meta transparent bottom30">
                <span><i class="icon-old-television"></i>TV Lounge</span>
                <span><i class="icon-garage"></i>1 Garage</span>
                <span></span>
              </div>
              <div class="favroute clearfix">
                <p><i class="icon-calendar2"></i>&nbsp;5 Days ago </p>
                <ul class="pull-right">
                  <li><a href="javascript:void(0)"><i class="icon-like"></i></a></li>
                  <li><a href="#seventy" class="share_expender" data-toggle="collapse"><i class="icon-share3"></i></a></li>
                </ul>
              </div>
              <div class="toggle_share collapse" id="seventy">
                <ul>
                  <li><a href="javascript:void(0)" class="facebook"><i class="icon-facebook-1"></i> Facebook</a></li>
                  <li><a href="javascript:void(0)" class="twitter"><i class="icon-twitter-1"></i> Twitter</a></li>
                  <li><a href="javascript:void(0)" class="vimo"><i class="icon-vimeo3"></i> Vimeo</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    <div class="col-sm-12 text-center top20">
       <a href="listing1.html" class="btn-dark border_radius uppercase margin40">more listings</a>
    </div>
  </div>
</section> -->
<!-- Gallery End -->


<!--Deals-->
<!-- <section id="deal" class="padding_bottom_half padding_top">
  <div class="container">
    <div class="row">
      <div class="col-sm-10">
        <h2 class="uppercase">Best Deal Properties</h2>
        <p class="heading_space">We have Properties in these Areas View a list of Featured Properties.</p>
      </div>
    </div>
    <div class="row">
      <div id="two-col-slider" class="owl-carousel">
        <div class="item">
          <div class="listing_full">
            <div class="image">
              <img alt="image" src="{% static 'images/b-d-property.jpg' %}">
              <span class="tag_t">For Sale</span>
            </div>
            <div class="listing_full_bg">
              <div class="listing_inner_full">
                <span><a href="#"><i class="icon-like"></i></a></span>
                <a href="property_detail1.html">
                  <h3>Park Avenue Apartment</h3>
                  <p>Towson London, MR 21501</p>
                </a>
                <div class="favroute clearfix">
                  <div class="property_meta"><span><i class="icon-select-an-objecto-tool"></i>4800 sq ft</span><span><i class=" icon-bed"></i>3 Bedrooms</span><span><i class="icon-safety-shower"></i>2 Bedrooms</span><span class="border-l">$38,600 / pm</span></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="listing_full">
            <div class="image">
              <img alt="image" src="{% static 'images/b-d-property2.jpg' %}">
              <span class="tag_t">For Sale</span>
            </div>
            <div class="listing_full_bg">
              <div class="listing_inner_full">
                <span><a href="#"><i class="icon-like"></i></a></span>
                <a href="property_detail2.html">
                  <h3>Park Avenue Apartment</h3>
                  <p>Towson London, MR 21501</p>
                </a>
                <div class="favroute clearfix">
                  <div class="property_meta"><span><i class="icon-select-an-objecto-tool"></i>4800 sq ft</span><span><i class=" icon-bed"></i>3 Bedrooms</span><span><i class="icon-safety-shower"></i>2 Bedrooms</span><span class="border-l">$38,600 / pm</span></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="listing_full">
            <div class="image">
              <img alt="image" src="{% static 'images/b-d-property3.jpg' %}">
              <span class="tag_t">For Sale</span>
            </div>
            <div class="listing_full_bg">
              <div class="listing_inner_full">
                <span><a href="#"><i class="icon-like"></i></a></span>
                <a href="property_detail3.html">
                  <h3>Park Avenue Apartment</h3>
                  <p>Towson London, MR 21501</p>
                </a>
                <div class="favroute clearfix">
                  <div class="property_meta"><span><i class="icon-select-an-objecto-tool"></i>4800 sq ft</span><span><i class=" icon-bed"></i>3 Bedrooms</span><span><i class="icon-safety-shower"></i>2 Bedrooms</span><span class="border-l">$38,600 / pm</span></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="listing_full">
            <div class="image">
              <img alt="image" src="{% static 'images/b-d-property4.jpg' %}">
              <span class="tag_t">For Sale</span>
            </div>
            <div class="listing_full_bg">
              <div class="listing_inner_full">
                <span><a href="#"><i class="icon-like"></i></a></span>
                <a href="property_detail1.html">
                  <h3>Park Avenue Apartment</h3>
                  <p>Towson London, MR 21501</p>
                </a>
                <div class="favroute clearfix">
                  <div class="property_meta"><span><i class="icon-select-an-objecto-tool"></i>4800 sq ft</span><span><i class=" icon-bed"></i>3 Bedrooms</span><span><i class="icon-safety-shower"></i>2 Bedrooms</span><span class="border-l">$38,600 / pm</span></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> -->
<!--Deals ends-->


<!--Parallax-->
<!-- <section id="parallax_four" class="padding">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 bottom30">
        <h2 class="uppercase">Over then <strong>7000</strong> Happy Customer</h2>
      </div>
      <div class="col-sm-8 col-md-10">
        <div class="row">
          <div class="col-sm-6 margin40">
             <i class="icon-presentation"></i>
             <h4 class="bottom10">Good Sale & Marketing</h4>
             <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam power nonummy nibh tempor cum soluta nobis eleifend.</p>
          </div>
          <div class="col-sm-6 margin40">
             <i class="icon-icons215"></i>
             <h4 class="bottom10">Good Sale & Marketing</h4>
             <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam power nonummy nibh tempor cum soluta nobis eleifend.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> -->
<!--About Owner ends-->


<!--Testinomials-->
<!-- <section id="testinomialBg" class="padding bg_light">
    <div id="agent-2" class="padding_bottom">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 text-center">
          <h2 class="uppercase">AGENTS YOU CAN TRUST</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec viverra erat Aenean elit tellus.</p>
        </div>
      </div>
      <div class="row">
        {% for agent in teams %}
        {% with profile=agent.profile %}
          <div class="col-sm-4 margin40">
            <div class="agent_wrap">
              <div class="image">
                <img src="{{profile.photo.url}}" alt="Agents">
                <div class="img-info">
                  <h3>{{agent.first_name}} {{agent.last_name}}</h3>
                  <span>{{profile.team.occupation}}</span>
                  <p class="top20 bottom30">{{profile.about}}</p>
                  <table class="agent_contact table">
                    <tbody>
                      <tr class="bottom10">
                        <td><strong>{% trans "Phone" %}:</strong></td>
                        <td class="text-right">{{profile.mobile}}</td>
                      </tr>
                      <tr>
                        <td><strong>{% trans "Email Adress" %}:</strong></td>
                        <td class="text-right"><a href="#.">{{agent.email}}</a></td>
                      </tr>
                    </tbody>
                  </table>
                  <hr>
                  <a class="btn-more" href="{% url "agent" agent.id %}">
                  <i><img alt="arrow" src="{% static 'images/arrow-yellow.png' %}"></i><span>Full Profile</span><i><img alt="arrow" src="{% static 'images/arrow-yellow.png' %}"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>
          {%endwith%}
        {% endfor %}
      </div>
    </div>
  </div>


{% show_happy_customer %}


</section> -->
<!--Testinomials ends-->


<!--Partners--> 
<!-- {% list_partners %} -->
<!-- Partners Ends -->

templates/castle/home/head.html
{% load static %}
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
<title>Castle</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}" >
<link rel="stylesheet" type="text/css" href="{% static 'css/reality-icon.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootsnav.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/owl.transitions.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/cubeportfolio.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.fancybox.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/settings.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/range-Slider.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}">
<link rel="icon" href="{% static 'images/icon.png' %}">
</head>

templates/castle/home/index.html

{% extends "base.html" %}
{% load static %}
 
 {% block header %}
  {% include 'navigation2/nav-home.html' %}
 {% endblock %} 
    
{% block content %}
  {%include 'home/content.html' with objs=objs%}
{% endblock %}


{% block domready %}
	<script src="{% static 'js/jquery-countTo.js' %}"></script>
{% endblock %}

templates/castle/home/search-form.html
    <form class="callus top30 clearfix centered" id="search_form" method="get" action="{% url "rentals:property_search" %}">
          <div class="row">
           
              <div class="col-sm-6">
                <div class="single-query form-group">
                  <input type="text" name='query' id='query' class="keyword-input" placeholder="Keyword (e.g. 'office')">
                </div>
              </div>
            
              <div class="col-sm-6">
                <div class="single-query form-group">
                  <input type="text" name='location' id='location' class="keyword-input" placeholder="Location (e.g. 'Gummersbach')">
                  {% comment %}
                 
                 {#  <div class="intro">
                     <select id="location", name="location">
                      <option value="" selected="">Location</option>
                      <option value="">All areas</option>
                      
                      {% for i in property %}
                      <option value="{{i.id}}">{{i.city}}</option>
                      {% endfor %}
                    </select>
                  </div> #}

                  {% endcomment %}
                </div>
              </div>
              
              <div class="col-sm-6">
                <div class="single-query form-group">
                  <div class="intro">
                    <select id="category", name="category">
                      <option value="" selected="">Property Type</option>
                      <option value="" >All type</option>
                      {% for i in property_category %}
                      <option value="{{i.id}}">{{i.title}}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="single-query form-group">
                  <div class="intro">
                    <select id="purpose" name="purpose">
                      <option value="" class="active">Purpose</option>
                      <option>All</option>
                     {% for key, value in property_purpose %}
                      <option value="{{key}}" {% if property_purpose == key %} selected {% endif %}>{{value}}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
              </div>

              <div class="col-sm-6">
                <div class="single-query form-group">
                  <div class="intro">
                    <input type="date" class="form-control" id="available_from" name="available_from">
                  </div>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="row search-2">
                  <div class="col-sm-6">
                    <div class="single-query form-group">
                      <div class="intro">
                        <select id="min_bed", name="min_bed"  >
                          <option value="0" >Min Beds</option>
                          <option value="1">1</option>
                          <option value="2" >2</option>
                          <option value="3" >3</option>
                          <option value="4" >4</option>
                          <option value="5" >5</option>
                          <option value="6" >6</option>
                        </select>
                      </div>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="single-query form-group">
                      <div class="intro">
                        <select id="min_bath", name="min_bath">
                          <option value="0" class="active">Min Baths</option>
                          <option value="1" >1</option>
                          <option value="2">2</option>
                          <option value="3">3</option>
                          <option value="4">4</option>
                          <option value="5">5</option>
                          <option value="6">6</option>
                        </select>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

            <div class="col-sm-6">
                <div class="row">
                  <div class="col-sm-6">
                    <div class="single-query form-group">
                      <input type="text" id="min_area"  name="min_area"  class="keyword-input" placeholder="Min Area (sq m)">
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="single-query form-group">
                      <input id="max_area" name="max_area" type="text"  class="keyword-input" placeholder="Max Area (sq m)">
                    </div>
                  </div>
                </div>
              </div>


                <div class="col-sm-6" style="display: none;">
                <div class="row">
                  <div class="col-sm-6">
                    <div class="single-query form-group">
                        <input type="text" id="min_price" style="display: none;" name="min_price" class="keyword-input" placeholder="Min price ">
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="single-query form-group">
                     
                         <input type="text" id="max_price" style="display: none;" name="max_price" class="keyword-input" placeholder="Max price">
                    </div>
                  </div>
                </div>
              </div>

         
             
              <div class="col-sm-12 bottom30">
                <div class="single-query-slider">
                  <label>Preisklasse:</label>
                  <div class="price text-right">
                    <span>€</span>
                    <div class="leftLabel"></div>
                    <span>to €</span>
                    <div class="rightLabel"></div>
                  </div>
               
                  <div data-range_min="0" data-range_max="{{max_price}}" data-cur_min="0" data-cur_max="{{max_price}}" class="nstSlider">
                    <div class="bar"></div>
                    <div class="leftGrip" ></div>
                    <div class="rightGrip"></div>
                  </div>
                </div>
              </div>
          
          </div>
          <div class="row">
            <div class="col-sm-6">
              <div class="group-button-search margin40">
                <a data-toggle="collapse" href=".html" class="more-filter">
                  <i class="fa fa-plus text-1 bg-color-yello" aria-hidden="true"></i>
                  <i class="fa fa-minus text-2 hide bg-color-yello" aria-hidden="true"></i>
                  <div class="text-1">Show more search options</div>
                  <div class="text-2 hide">less more search options</div>
                </a>
              </div>
            </div>
            <div class="col-sm-6 form-group top20 text-right">
                 <input class="btn-blue border_radius" type="submit" value="Suchen">

            </div>
          </div>
          <div class="search-propertie-filters collapse">
            <div class="container-2 bottom30">
              <div class="row">
                <div class="col-md-4 col-sm-6">
                  <div class="search-form-group white">
                    <input type="checkbox" name="check-box" />
                    <span>Washer and Dryer</span>
                  </div>
                </div>
                <div class="col-md-4 col-sm-6">
                  <div class="search-form-group white">
                    <input type="checkbox" name="check-box" />
                    <span>Washer and Dryer</span>
                  </div>
                </div>
                <div class="col-md-4 col-sm-6">
                  <div class="search-form-group white">
                    <input type="checkbox" name="check-box" />
                    <span>Washer and Dryer</span>
                  </div>
                </div>
                <div class="col-md-4 col-sm-6">
                  <div class="search-form-group white">
                    <input type="checkbox" name="check-box" />
                    <span>Balcony</span>
                  </div>
                </div>
                <div class="col-md-4 col-sm-6">
                  <div class="search-form-group white">
                    <input type="checkbox" name="check-box" />
                    <span>Balcony</span>
                  </div>
                </div>
                <div class="col-md-4 col-sm-6">
                  <div class="search-form-group white">
                    <input type="checkbox" name="check-box" />
                    <span>Balcony</span>
                  </div>
                </div>
                <div class="col-md-4 col-sm-6">
                  <div class="search-form-group white">
                    <input type="checkbox" name="check-box" />
                    <span>Storage</span>
                  </div>
                </div>
                <div class="col-md-4 col-sm-6">
                  <div class="search-form-group white">
                    <input type="checkbox" name="check-box" />
                    <span>Storage</span>
                  </div>
                </div>
                <div class="col-md-4 col-sm-6">
                  <div class="search-form-group white">
                    <input type="checkbox" name="check-box" />
                    <span>Storage</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
</form>