castle/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url, include, handler400, handler500
from django.conf import settings
from django.conf.urls.static import static
from . import views
from rentals import urls
from profiles import views as team

urlpatterns = [
    path('cp/', admin.site.urls),
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    url('^$', views.home, name='home'),
    url(r'^backoffice/', include('backoffice.urls')),
    # url('^contacts$', views.contacts, name='contacts'),
    url(r'^rentals/', include('rentals.urls')),
    url(r'^news/',    include('news.urls', namespace="news")),
    # url(r'^404$',views.error_404, name='error_404'),
    url(r'^faq/$', views.faq, name='faq'),
    # path('profile/', include('profiles.urls', namespace="profile")),
    path('account/',  include('account.urls', namespace='account')),
    path('profile/',  include('profiles.urls', namespace='profile')),
    path('accounts/', include('allauth.urls')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    # path('teams/',    include('agents.urls', namespace='teams')),
    # path('additions/', include('additions.urls', namespace='additions')),
    url(r'$send/$', views.send_mail, name="send-mail" ),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('teams/', team.list_agents, name='agents'),
    path('team/<int:id>', team.detail_agent, name='agent'),
    # url(r'^imagefit/', include('imagefit.urls')),

]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'castle.views.handler404'
handler500 = 'castle.views.handler500'

news/urls.py
from django.conf.urls import url 
from . import views
from django.urls import path

app_name = 'news'
urlpatterns = [
	url(r'^$', views.list, name='list'),
	path('detail/<slug:slug>/', views.detail, name='detail'),
	path('tag/<slug:tag_slug>/', views.list, name='post_list_by_tag'), 
	path('cat/<slug:cat_slug>/', views.list, name='list_post_by_category'), 
	path('search/', views.post_search, name='search'),
]

castle/views.py
from django.shortcuts import render
from django.core.mail import BadHeaderError, send_mail
from django.http      import HttpResponse, HttpResponseRedirect
from additions.models import FAQ
from rentals.models   import Properties
from profiles.models  import Team 
from contacts.models  import Emails
from django.contrib.auth.models import User
from django.views.decorators.cache import cache_page
from django.views.decorators.vary  import vary_on_cookie
# from django.templates import RequestContext

@vary_on_cookie
@cache_page(60)
def home(request):
	hauses     = Properties.objects.all()[9:]
	print(hauses)
	teams    = User.objects.filter(is_active=True, is_staff=True)[3:] 
	featured = Properties.objects.filter(featured=True)[10:]
	
	return render(request, 'home/index.html',{
		'hauses':hauses,
		'teams':teams,
		'featured':featured})

@vary_on_cookie
@cache_page(3600)
def contacts(request):
	return render(request, 'contacts/contact.html',{})

@vary_on_cookie
@cache_page(3600)
def faq(request):
	faq = FAQ.objects.filter(is_active=True)
	# faq = FAQ.objects.all()
	return render(request, 'faq/faq.html', {'faq':faq})


def error_404(request):
	return render(request, 'errors/404.html')

def handler404(request, exception):
	return render(request, '404.html', {})

def handler500(request, *args, **kwargs):
	return render(request, '500.html', {})


def send_mail(request):
	subject = request.POST.get('subject','')
	message = request.POST.get('message', '')
	from_email= request.POST.get("from_email","")
	if subject and message and from_email:
		try:
			print('email has been sent successfully')
			send_mail(subject, message, from_email, ['admin@example.com'])
		except:
			return HttpResponse('Invalid header found.')
		return HttpResponseRedirect('/contact/thanks/')
	else:
		return HttpResponse('Make sure all fields are entered and valid.')	

			

templates/castle/template_tags/featured.html
 {% load static %}
 {% load i18n %}
 
  <div class="col-md-12">
      <h3 class="margin40 bottom20">{% trans "Featured Properties" %}</h3>
  </div>
  <div class="col-md-12">
  <div id="agent-2-slider" class="owl-carousel">
    {% for fet in featured %}
      <div class="item">
        <div class="property_item heading_space">
          <div class="image">
            <a href="#"><img src="{% static 'images/slider-list2.jpg' %}" alt="listin" class="img-responsive"></a>
            <div class="feature"><span class="tag-2">{% trans "For" %} {% ifequal fet.prop.purpose 0 %}{%trans "Rent" %}{% else %}{% trans "Sale" %} {% endifequal %}</span></div>
            <div class="price clearfix"><span class="tag pull-right">{{fet.prop.price}} Per Month - <small>{{fet.prop.short_description}}</small></span></div>
          </div>
        </div>
      </div>
      {% endfor %}
    

    </div>
  </div> 

templates/castle/template_tags/featured2.html

              <div class="row">
                 <div class="col-md-12">
                    <h3 class="bottom40 margin40">Featured Properties</h3>
                 </div>
              </div>
              <div class="row">
                 <div class="col-md-4 col-sm-4 col-xs-12 p-image image bottom20">
                    <img src="{% static 'images/f-p-1.png' %}" alt="image"/>
                 </div>
                 <div class="col-md-8 col-sm-8 col-xs-12">
                    <div class="feature-p-text">
                       <h4><a href="#.">Get the best property in Town by our agent</a></h4>
                       <span>by Martin Moore</span>
                    </div>
                 </div>
              </div>
              <div class="row padding-b-30 padding-t-30">
                 <div class="col-md-4 col-sm-4 col-xs-12 p-image image bottom20">
                    <img src="{% static 'images/f-p-1.png' %}" alt="image"/>
                 </div>
                 <div class="col-md-8 col-sm-8 col-xs-12">
                    <div class="feature-p-text">
                       <h4><a href="#.">Get the best property in Town by our agent</a></h4>
                       <span>by Martin Moore</span>
                    </div>
                 </div>
              </div>
              <div class="row">
                 <div class="col-md-4 col-sm-4 col-xs-12 p-image image">
                    <img src="{% static 'images/f-p-1.png' %}" alt="image"/>
                 </div>
                 <div class="col-md-8 col-sm-8 col-xs-12">
                    <div class="feature-p-text">
                       <h4><a href="#.">Get the best property in Town by our agent</a></h4>
                       <span>by Martin Moore</span>
                    </div>
                 </div>
              </div>

templates/castle/template_tags/featured_posts.html
 {% load static %}  
    <div class="row bottom20">
      <div class="col-md-4 col-sm-4 col-xs-6 p-image">
        <img src="{% static 'images/f-p-1.png' %}" alt="image"/>
      </div>
      
      <div class="col-md-8 col-sm-8 col-xs-6">
        <div class="feature-p-text">
          <h4>Historic Town House</h4>
          <p class="bottom15">45 Regent Street, London, UK</p>
          <a href="#.">$128,600</a>
        </div>
      </div>
    </div>
         

templates/castle/template_tags/featured_posts2.html
              <div class="row">
                 <div class="col-md-12">
                    <h3 class="bottom40 margin40">Featured Properties</h3>
                 </div>
              </div>
              <div class="row">
                 <div class="col-md-4 col-sm-4 col-xs-12 p-image image bottom20">
                    <img src="{% static 'images/f-p-1.png' %}" alt="image"/>
                 </div>
                 <div class="col-md-8 col-sm-8 col-xs-12">
                    <div class="feature-p-text">
                       <h4><a href="#.">Get the best property in Town by our agent</a></h4>
                       <span>by Martin Moore</span>
                    </div>
                 </div>
              </div>
              <div class="row padding-b-30 padding-t-30">
                 <div class="col-md-4 col-sm-4 col-xs-12 p-image image bottom20">
                    <img src="{% static 'images/f-p-1.png' %}" alt="image"/>
                 </div>
                 <div class="col-md-8 col-sm-8 col-xs-12">
                    <div class="feature-p-text">
                       <h4><a href="#.">Get the best property in Town by our agent</a></h4>
                       <span>by Martin Moore</span>
                    </div>
                 </div>
              </div>
              <div class="row">
                 <div class="col-md-4 col-sm-4 col-xs-12 p-image image">
                    <img src="{% static 'images/f-p-1.png' %}" alt="image"/>
                 </div>
                 <div class="col-md-8 col-sm-8 col-xs-12">
                    <div class="feature-p-text">
                       <h4><a href="#.">Get the best property in Town by our agent</a></h4>
                       <span>by Martin Moore</span>
                    </div>
                 </div>
              </div>

templates/castle/template_tags/happy_customers.html
 {% load static %}   
    <div class="container bg_white padding">
      <div class="row">
        <div class="col-xs-12 text-center">
          <h2 class="uppercase">Happy Customers</h2>
          <p class="heading_space">What our clients say about us.</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
           <div id="testinomial-slider" class="owl-carousel display navigate">
            {% for c in customers %}
              <div class="item">
                <div class="testinomial_content text-center">
                  <img src="{{ c.image.url }}" alt="happy client" class="bottom15">
                 <h4 class="uppercase">{{c.full_name}}</h4>
                 <span class="smmery bottom15">( {{c.company}}  )</span>
                 <img src="{% static 'images/stars.png' %}" alt="rating" class="bottom30">
                 <p>{{c.comment|safe}}</p>
                </div>
              </div>
            {% endfor %}
 
          </div>
        </div>
      </div>
    </div>

templates/castle/template_tags/partners_list.html
{% load static %}
{% load i18n %}

<section id="logos">
  <div class="container partner2 padding">
    <div class="row">
      <div class="col-sm-12 text-center">
        <h2 class="uppercase">Our Partners</h2>
        <p class="heading_space">Aliquam nec viverra erat. Aenean elit tellus mattis quis maximus.</p>
      </div>
    </div>
    <div class="row">
    <div id="partners" class="owl-carousel">
      {% for p in partners %}
        <div class="item">
          <img src="{{ p.logo.url }}" alt="Featured Partner">
        </div>
      {% endfor %}  

      </div>
    </div>
  </div>
</section>

templates/castle/template_tags/partners_list2.html
  {% load static %}
  {% load i18n %}
  <section id="logos">
    <div class="container partners padding_top">
      <div class="row">
        <div class="col-sm-12 text-center">
          <h2 class="uppercase">{% trans "Our Partners" %}</h2>
          <p class="heading_space" {% trans 'Aliquam nec viverra erat. Aenean elit tellus mattis quis maximus.' %}</p>
        </div>
      </div>
      <div class="row">
        <div id="partner-slider" class="owl-carousel">
          {% for p in partners %}
            <div class="item">
              <img src="{{p.logo.url }}" alt="{{p.partner_name}}">
            </div>
          {% endfor %}
          
        </div>
      </div>
    </div>
  </section>

templates/castle/template_tags/post_categories.html
<ul class="pro-list padding-t-20">

   {% for cat in cats %}
      <li>
      	<a href="{% url 'news:list_post_by_category' cat.slug %}">{{cat}}</a>
      </li>
   {% endfor %}         
</ul>