account/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name    = 'account'
urlpatterns = [
	path('login/', auth_views.LoginView.as_view(), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
	path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
	path('profile/', views.profile, name='profile'),
	path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('account:password_reset_done')), name='password_reset'),
	path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
	path('register/', views.register, name='register'),
]

backoffice/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, include
from .views import index, search_and_filter, new_property, create_property_picture, create_property_category, create_feature, manage_properties, property_picture, manage_property_picture, delete_property_picture, property_category, manage_property_category, delete_property_category, manage_feature, propertyDeleteView, features, delete_feature 
# from .views import PictureList, PicturePropertyCreate


app_name = 'backoffice'
urlpatterns = [

  path('', index, name='index'),
  path('allproperty/', views.allproperty, name='allproperty'),
  path('activeproperty/', views.activeproperties, name='activeproperties'),
  path('propertyforsale/', views.propertyforsale, name='propertyforsale'),
  path('propertyforrent/', views.propertyforrent, name='propertyforrent'),

  path('search_and_filter/', search_and_filter, name='ajax_search_and_filter'),
  path('new_property/', new_property, name='new_property'),
  path('uploadpicture/', views.uploadpicture, name='uploadpicture'),
  path('manage_properties/<int:id>/', manage_properties, name='manage_properties'),
  path('delete/', propertyDeleteView, name='deleteproperty'),
  path('change_status/', views.change_status, name='changestatus'),
  path('features/', features, name='features'),
  path('create_feature/', create_feature, name='create_feature'),

  
  path('features/<int:id>/', manage_feature, name='managefeature'),
  path('delete_feature/', delete_feature, name='deletefeature'),
  path('property_categories/', property_category, name='property_categories'),
  path('create_property_category/', create_property_category, name='create_property_category'),
  # path('^fine-uploader/', include('django_fine_uploader.urls', namespace='django_fine_uploader')),

  
  path('property_categories/<int:id>/', manage_property_category, name='manage_property_category'),
  path('delete_property_category/', delete_property_category, name='delete_property_category'),

  path('property_pictures/', property_picture, name='property_pictures'),
  path('create_property_picture/', create_property_picture, name='create_property_picture'),

  # path('basic-upload/$', views.BasicUploadView.as_view(), name='basic_upload'),

  path('property_pictures/<int:id>/', manage_property_picture, name='manage_property_picture'),
  path('delete_property_pictures/', delete_property_picture, name='delete_property_picture'),


  path('show_messages/', views.not_replied_messages, name='show_new_messages'),
  path('all_messages/', views.show_all_messages, name='all_messages'),
  path('search_message/', views.search_message, name='search_message'),
  
  path('delete_message/', views.delete_message, name='delete_message'),
  # url(r'ckeditor/', include('ckeditor_uploader.urls')),
  path('send_property_list/', views.send_property, name='send_property_list'),

  path('social_contact', views.social_contact, name='social_contact'),
  path('create_social_contact', views.create_social_contact, name='create_social_contact'),
  path('social_contact/<int:id>/', views.manage_social_contact, name='manage_social_contact'),
  path('delete_social_contact/', views.delete_social_contact, name='delete_social_contact'),
  

  path('contact_number', views.contact_number, name='contact_number'),
  path('create_contact_number', views.create_contact_number, name='create_contact_number'),
  path('contact_number/<int:id>/', views.manage_contact_number, name='manage_contact_number'),
  path('delete_contact_number/', views.delete_contact_number, name='delete_contact_number'),
  
  path('twillo', views.twillo, name='twillo'),
  path('create_twillo', views.create_twillo, name='create_twillo'),
  path('twillo/<int:id>/', views.manage_twillo, name='manage_twillo'),
  path('delete_twillo/', views.delete_twillo, name='delete_twillo'),
  




]

castle/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url, include, handler400, handler500
from django.conf import settings
from django.conf.urls.static import static
from . import views
from rentals import urls
from profiles import views as team

urlpatterns = [
    path('cp/', admin.site.urls),
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    url('^$', views.home, name='home'),
    url(r'^backoffice/', include('backoffice.urls')),
    # url('^contacts$', views.contacts, name='contacts'),
    url(r'^rentals/', include('rentals.urls')),
    url(r'^news/',    include('news.urls', namespace="news")),
    # url(r'^404$',views.error_404, name='error_404'),
    url(r'^faq/$', views.faq, name='faq'),
    # path('profile/', include('profiles.urls', namespace="profile")),
    path('account/',  include('account.urls', namespace='account')),
    path('profile/',  include('profiles.urls', namespace='profile')),
    path('accounts/', include('allauth.urls')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    # path('teams/',    include('agents.urls', namespace='teams')),
    # path('additions/', include('additions.urls', namespace='additions')),
    url(r'$send/$', views.send_mail, name="send-mail" ),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('teams/', team.list_agents, name='agents'),
    path('team/<int:id>', team.detail_agent, name='agent'),
    # url(r'^imagefit/', include('imagefit.urls')),

]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'castle.views.handler404'
handler500 = 'castle.views.handler500'

news/urls.py
from django.conf.urls import url 
from . import views
from django.urls import path

app_name = 'news'
urlpatterns = [
	url(r'^$', views.list, name='list'),
	path('detail/<slug:slug>/', views.detail, name='detail'),
	path('tag/<slug:tag_slug>/', views.list, name='post_list_by_tag'), 
	path('cat/<slug:cat_slug>/', views.list, name='list_post_by_category'), 
	path('search/', views.post_search, name='search'),
]

profiles/urls.py
from django.urls import path 
from . import views

app_name='profile'
urlpatterns = [
	path('login/', views.user_login, name='login'),
	path('', views.profile, name='profile'),
	path('edit/', views.edit, name='edit'),
	path('favorites/', views.list_favorites, name='favorites'),
	path('add_fav/', views.add_to_favorities, name='add_fav'),
	path('admin/contacts/<int:email_id>/', views.admin_email_detail, name='admin_email_detail'),

]

castle/views.py
from django.shortcuts import render
from django.core.mail import BadHeaderError, send_mail
from django.http      import HttpResponse, HttpResponseRedirect
from additions.models import FAQ
from rentals.models   import Properties
from profiles.models  import Team 
from contacts.models  import Emails
from django.contrib.auth.models import User
from django.views.decorators.cache import cache_page
from django.views.decorators.vary  import vary_on_cookie
# from django.templates import RequestContext

@vary_on_cookie
@cache_page(60)
def home(request):
	hauses     = Properties.objects.all()[9:]
	print(hauses)
	teams    = User.objects.filter(is_active=True, is_staff=True)[3:] 
	featured = Properties.objects.filter(featured=True)[10:]
	
	return render(request, 'home/index.html',{
		'hauses':hauses,
		'teams':teams,
		'featured':featured})

@vary_on_cookie
@cache_page(3600)
def contacts(request):
	return render(request, 'contacts/contact.html',{})

@vary_on_cookie
@cache_page(3600)
def faq(request):
	faq = FAQ.objects.filter(is_active=True)
	# faq = FAQ.objects.all()
	return render(request, 'faq/faq.html', {'faq':faq})


def error_404(request):
	return render(request, 'errors/404.html')

def handler404(request, exception):
	return render(request, '404.html', {})

def handler500(request, *args, **kwargs):
	return render(request, '500.html', {})


def send_mail(request):
	subject = request.POST.get('subject','')
	message = request.POST.get('message', '')
	from_email= request.POST.get("from_email","")
	if subject and message and from_email:
		try:
			print('email has been sent successfully')
			send_mail(subject, message, from_email, ['admin@example.com'])
		except:
			return HttpResponse('Invalid header found.')
		return HttpResponseRedirect('/contact/thanks/')
	else:
		return HttpResponse('Make sure all fields are entered and valid.')	

			

templates/castle/navigation/advanced_search.html
<button type="button" class="form_opener"><i class="fa fa-bars"></i></button>
<div class="tp_overlay">
  <div class="topbar clearfix">
    <ul class="breadcrumb_top">
      <li><a href="{% url 'profile:favorites' %}"><i class="icon-icons43"></i>Favorites</a></li>
       {% if request.user.is_staff %}<li><a href="{% url 'backoffice:index' %}"><i class="icon-icons215"></i>Backoffice</a></li>{%endif%}
       {% if request.user.is_staff %}<li><a href="{% url "profile:profile" %}"><i class="icon-icons215"></i>My Property</a></li>{% endif %}
       {% if request.user.is_authenticated %}
              <li><a href="{% url "account:profile" %}"><i class="icon-icons230"></i>{{request.user.username}}</a></li>
            {% endif %}
              <li>
                <a href="{% if request.user.is_authenticated %}{% url 'account_logout' %}{% else %}/accounts/login{% endif %}">
                  <i class="icon-icons179"></i>
                    {% if request.user.is_authenticated %}Logout{% else %}Login/Register{% endif %}</a>
              </li>
    </ul>
  </div>
      {% include 'home/search-form.html' %}
</div>

templates/castle/navigation/nav-home.html
{% load sitetree %}
{% load static %}

<header class="layout_boxed">
  <div class="topbar">
    <div class="container">
      <div class="row">
        <div class="col-md-5">
          <p>We are Best in Town With 40 years of Experience.</p>
        </div>
        <div class="col-md-7 text-right">
          <ul class="breadcrumb_top text-right">
            <li><a href="{% url 'profile:favorites' %}"><i class="icon-icons43"></i>Favorites</a></li>
             {% if request.user.is_staff %}<li><a href="{% url 'backoffice:index' %}"><i class="icon-icons215"></i>Backoffice</a></li>{%endif%}
              {% if request.user.is_staff %}<li><a href="{% url "profile:profile" %}"><i class="icon-icons215"></i>My Property(UD)</a></li>{% endif %}
            {% if request.user.is_authenticated %}
              <li><a href="{% url "account:profile" %}"><i class="icon-icons230"></i>{{request.user.username}}</a></li>
            {% endif %}
              <li>
                <a href="{% if request.user.is_authenticated %}{% url 'account_logout' %}{% else %}/accounts/login{% endif %}">
                  <i class="icon-icons179"></i>
                    {% if request.user.is_authenticated %}Logout{% else %}Login/Register{% endif %}</a>
              </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="header-upper dark">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-12">
          <div class="logo">
            <a href="index6.html"><img alt="" src=" {% static "images/logo-white.png" %}"></a>
          </div>
        </div>
        <!--Info Box-->
        <div class="col-md-9 col-sm-12 right">
          <div class="info-box first">
            <div class="icons"><i class="icon-telephone114"></i></div>
            <ul>
              <li><strong>Phone Number</strong></li>
              <li>+1 900 234 567 - 68</li>
            </ul>
          </div>
          <div class="info-box">
            <div class="icons"><i class="icon-icons74"></i></div>
            <ul>
              <li><strong>Manhattan Hall,</strong></li>
              <li>Castle Melbourne, australia</li>
            </ul>
          </div>
          <div class="info-box">
            <div class="icons"><i class="icon-icons142"></i></div>
            <ul>
              <li><strong>Email Address</strong></li>
              <li><a href="javascript:void(0)">info@castle.com</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-default navbar-sticky bootsnav">
    <div class="container">
      <div class="attr-nav">
        <a href="#." class="btn-touch uppercase white-touch">Get in Touch</a>
      </div>
      <div class="attr-nav">
        <ul class="social_share">
          <li><a href="javascript:void(0)" class="facebook"><i class="fa fa-facebook"></i></a></li>
          <li><a href="javascript:void(0)" class="twitter"><i class="fa fa-twitter"></i></a></li>
          <li><a class="google" href="javascript:void(0)"><i class="icon-google4"></i></a></li>
        </ul>
      </div>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
        <i class="fa fa-bars"></i>
        </button>
        <a class="navbar-brand sticky_logo" href="index6.html"><img src=" {% static "images/logo-white.png" %} " class="logo" alt=""></a>
      </div>
      <div class="collapse navbar-collapse" id="navbar-menu">
        <ul class="nav navbar-nav" data-in="fadeIn" data-out="fadeOut">
              {% sitetree_menu  from  'menu' include "trunk,1,level3" template "navigation/navs.html" %}
         </ul>
      </div>
    </div>
  </nav>
</header>

templates/castle/navigation/nav-item.html
 {% load sitetree %}
  {% for item in sitetree_items %}
    
       <li class="dropdown">
          <a href="{% sitetree_url for item %}" {% if item.has_children %}  class="dropdown-toggle" data-toggle="dropdown" {%endif%}>{{item.title_resolved}}</a>
         <ul class="dropdown-menu animated fadeOut" style="display: none; opacity: 1;">
           {% if item.has_children%}
            {% sitetree_children of item for menu template "navigation/nav-item.html" %}
           {%endif%}
         </ul>
      </li>
   
  {% endfor %}


templates/castle/navigation/nav-item2.html
      <li>
                    <div class="row">
                      <div class="col-menu col-md-3">
                        <h5 class="title">PROPERTY LISTINGS</h5>
                        <div class="content">
                          <ul class="menu-col">
                            <li><a href="listing1.html">List Style 1</a></li>
                            <li><a href="listing2.html">List Style 2</a></li>
                            <li><a href="listing3.html">List Style 3</a></li>
                            <li><a href="listing4.html">List Style 4</a></li>
                            <li><a href="listing5.html">List Style 5</a></li>
                          </ul>
                        </div>
                      </div>
                      <div class="col-menu col-md-3">
                        <h5 class="title">PROPERTY LISTINGS</h5>
                        <div class="content">
                          <ul class="menu-col">
                            <li><a href="listing6.html">List Style 5</a></li>
                            <li><a href="listing7.html">List Style 6</a></li>
                            <li><a href="listing1.html">Search by City</a></li>
                            <li><a href="listing2.html">Search by Category</a></li>
                            <li><a href="listing3.html">Search by Type</a></li>
                          </ul>
                        </div>
                      </div>
                      <div class="col-menu col-md-3">
                        <h5 class="title">PROPERTY DETAIL</h5>
                        <div class="content">
                          <ul class="menu-col">
                            <li><a href="property_detail1.html">Property Detail 1</a></li>
                            <li><a href="property_detail2.html">Property Detail 2</a></li>
                            <li><a href="property_detail3.html">Property Detail 3</a></li>
                            <li><a href="index7.html">Single Property</a></li>
                            <li><a href="listing4.html">Search by Type</a></li>
                          </ul>
                        </div>
                      </div>
                      <div class="col-menu col-md-3">
                        <h5 class="title">OTHER PAGES</h5>
                        <div class="content">
                          <ul class="menu-col">
                            <li><a href="favorite_properties.html">Favorite Properties</a></li>
                            <li><a href="agent_profile.html">Agent Profile</a></li>
                            <li><a href="404.html">404 Error</a></li>
                            <li><a href="contact.html">Contact Us</a></li>
                            <li><a href="testimonial.html">Testimonials</a></li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </li>

templates/castle/navigation/nav-item3.html
                  <li>
                    <div class="row">
                      <div class="col-menu col-md-3">
                        <h5 class="title">PROPERTIES LIST</h5>
                        <div class="content">
                          <ul class="menu-col">
                            <li><a href="listing1.html">Properties List</a></li>
                            <li><a href="index7.html">Single Property</a></li>
                            <li><a href="listing2.html">Search by City</a></li>
                            <li><a href="listing5.html">Search by Category</a></li>
                            <li><a href="listing3.html">Search by Type</a></li>
                          </ul>
                        </div>
                      </div>
                      <div class="col-menu col-md-9">
                        <h5 class="title bottom20">PROPERTIES LIST</h5>
                        <div class="row">
                          <div id="nav_slider" class="owl-carousel">
                            <div class="item">
                              <div class="image bottom15"> 
                                <img src="{% static 'images/nav-slider1.jpg' %}" alt="Featured Property"> 
                                <span class="nav_tag yellow text-uppercase">for rent</span>
                              </div>
                              <h4><a href="property_detail1.html">Park Avenue Apartment</a></h4>
                              <p>Towson London, MR 21501</p>
                            </div>
                            <div class="item">
                              <div class="image bottom15"> 
                                <img src="{% static 'images/nav-slider2.jpg' %}" alt="Featured Property"> 
                                <span class="nav_tag yellow text-uppercase">for rent</span>
                              </div>
                              <h4><a href="property_detail2.html">Park Avenue Apartment</a></h4>
                              <p>Towson London, MR 21501</p>
                            </div>
                            <div class="item">
                              <div class="image bottom15"> 
                                <img src="{% static 'images/nav-slider3.jpg' %}" alt="Featured Property"> 
                                <span class="nav_tag yellow text-uppercase">for rent</span>
                              </div>
                              <h4><a href="property_detail3.html">Park Avenue Apartment</a></h4>
                              <p>Towson London, MR 21501</p>
                            </div>
                            <div class="item">
                              <div class="image bottom15"> 
                                <img src="{% static 'images/nav-slider1.jpg' %}" alt="Featured Property"> 
                                <span class="nav_tag yellow text-uppercase">for rent</span>
                              </div>
                              <h4><a href="property_detail1.html">Park Avenue Apartment</a></h4>
                              <p>Towson London, MR 21501</p>
                            </div>
                            <div class="item">
                              <div class="image bottom15"> 
                                <img src="{% static 'images/nav-slider2.jpg' %}" alt="Featured Property"> 
                                <span class="nav_tag yellow text-uppercase">for rent</span>
                              </div>
                              <h4><a href="property_detail2.html">Park Avenue Apartment</a></h4>
                              <p>Towson London, MR 21501</p>
                            </div>
                            <div class="item">
                              <div class="image bottom15"> 
                                <img src="{% static 'images/nav-slider3.jpg' %}" alt="Featured Property"> 
                                <span class="nav_tag yellow text-uppercase">for rent</span>
                              </div>
                              <h4><a href="property_detail3.html">Park Avenue Apartment</a></h4>
                              <p>Towson London, MR 21501</p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </li>

templates/castle/navigation/nav-sub-item.html
{% load sitetree %}
 {% for item in sitetree_items %}
  <li><a href="{% sitetree_url for item %}">{{item.title_resolved}}</a></li>
{% endfor %}

templates/castle/navigation/nav.html
{% load static %}
{% load sitetree %}
  <nav class="navbar navbar-default navbar-sticky bootsnav">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="attr-nav">
            <ul class="social_share clearfix">
              <li wfd-id="299"><a href="javascript:void(0)" class="facebook"><i class="fa fa-facebook"></i></a></li>
              <li wfd-id="298" ><a href="javascript:void(0)" class="twitter"><i class="fa fa-twitter"></i></a></li>
              <li wfd-id="297"><a class="google" href="javascript:void(0)"><i class="icon-google4"></i></a></li>
            </ul>
          </div>
          <!-- Start Header Navigation -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
            <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand sticky_logo" href="index3.html"><img src="{% static 'images/logo-white.png' %}" class="logo" alt=""></a>
          </div> <!-- End Header Navigation -->
          
          

          <div class="collapse navbar-collapse" id="navbar-menu">
            <ul class="nav navbar-nav" data-in="fadeIn" data-out="fadeOut">
              {% sitetree_menu  from  'menu' include "trunk" template "navigation/navs.html" %}
            </ul>
          </div>
        


        </div>
      </div>
    </div>
  </nav>

templates/castle/navigation/navs.html
{% load sitetree %}
{%for item in sitetree_items %}
<li {%if item.has_children %} class="dropdown" {%endif%}>
    <a href="{% sitetree_url for item %}" class="dropdown-toggle" data-toggle="dropdown">{{ item.title_resolved }} </a>
      <ul class="dropdown-menu animated fadeOut" style="display: none; opacity: 1;">

       {% if item.has_children %}
          {% sitetree_children of item for menu template 'navigation/nav-item.html'%}
       {% endif %}
     
      </ul>
  </li>


{%endfor%}

templates/castle/navigation/slider.html
{% load static %}
<div class="rev_slider_wrapper">
  <div id="rev_overlaped" class="rev_slider"  data-version="5.0">
    <ul>
      <!-- SLIDE -->
      <li data-transition="fade">
        <img src="{% static 'images/home1-banner1.jpg' %}" alt="" data-bgposition="center center" data-bgfit="cover" class="rev-slidebg">							
      </li>
      <li data-transition="fade">
        <img src="{% static 'images/home1-banner2.jpg' %}" alt="" data-bgposition="center center" data-bgfit="cover" class="rev-slidebg">							
      </li>
      <li data-transition="fade">
        <img src="{% static 'images/home1-banner3.jpg' %}" alt="" data-bgposition="center center" data-bgfit="cover" class="rev-slidebg">							
      </li>
      <div class="tp-static-layers">
        <div class="tp-caption tp-static-layer" 
          id="slide-37-layer-2" 
          data-x="['left','left','left','left']" data-hoffset="['50','50','50','50']" 
          data-y="['bottom','bottom','bottom','bottom']" data-voffset="['230','180','150','100']"  
          data-whitespace="nowrap"
          data-visibility="['on','on','on','on']"
          data-fontsize="['48','48','28','28']"
          data-start="500" 
          data-responsive_offset="on"
          data-basealign="slide" 
          data-startslide="0" 
          data-endslide="5" 
          style="z-index: 5;">
          <h1><span class="t_white">We Can Find just Right <br>Property for You.</span></h1>
        </div>
        <div class="tp-caption tp-static-layer" 
          id="slide-37-layer-2" 
          data-x="['left','left','left','left']" data-hoffset="['50','50','50','50']" 
          data-y="['bottom','bottom','bottom','bottom']" data-voffset="['150','100','120','120']" 
          data-whitespace="nowrap"
          data-visibility="['on','on','on','on']"
          data-start="500" 
          data-basealign="slide" 
          data-startslide="0" 
          data-endslide="5" 
          style="z-index: 5;">
          <p class="t_white">We Deal with Different kinds of Properties No matter you need a House, 
            an Apartment or garage. <br> You’ll find a good option on our Theme.
          </p>
        </div>
        <div class="tp-caption tp-static-layer" 
          id="slide-37-layer-2" 
          data-x="['left','left','left','left']" data-hoffset="['50','50','50','50']" 
          data-y="['bottom','bottom','bottom','bottom']" data-voffset="['60','60','60','60']" 
          data-whitespace="nowrap"
          data-visibility="['on','on','on','on']"
          data-start="500" 
          data-basealign="slide" 
          data-startslide="0" 
          data-endslide="5" 
          style="z-index: 5;"><a href="listing1.html" class="btn-white border_radius uppercase">view Properties</a>
        </div>
      </div>
    </ul>
  </div>
</div>