castle/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url, include, handler400, handler500
from django.conf import settings
from django.conf.urls.static import static
from . import views
from rentals import urls
from profiles import views as team

urlpatterns = [
    path('cp/', admin.site.urls),
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    url('^$', views.home, name='home'),
    url(r'^backoffice/', include('backoffice.urls')),
    # url('^contacts$', views.contacts, name='contacts'),
    url(r'^rentals/', include('rentals.urls')),
    url(r'^news/',    include('news.urls', namespace="news")),
    # url(r'^404$',views.error_404, name='error_404'),
    url(r'^faq/$', views.faq, name='faq'),
    # path('profile/', include('profiles.urls', namespace="profile")),
    path('account/',  include('account.urls', namespace='account')),
    path('profile/',  include('profiles.urls', namespace='profile')),
    path('accounts/', include('allauth.urls')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    # path('teams/',    include('agents.urls', namespace='teams')),
    # path('additions/', include('additions.urls', namespace='additions')),
    url(r'$send/$', views.send_mail, name="send-mail" ),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('teams/', team.list_agents, name='agents'),
    path('team/<int:id>', team.detail_agent, name='agent'),
    # url(r'^imagefit/', include('imagefit.urls')),

]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'castle.views.handler404'
handler500 = 'castle.views.handler500'

news/urls.py
from django.conf.urls import url 
from . import views
from django.urls import path

app_name = 'news'
urlpatterns = [
	url(r'^$', views.list, name='list'),
	path('detail/<slug:slug>/', views.detail, name='detail'),
	path('tag/<slug:tag_slug>/', views.list, name='post_list_by_tag'), 
	path('cat/<slug:cat_slug>/', views.list, name='list_post_by_category'), 
	path('search/', views.post_search, name='search'),
]

profiles/urls.py
from django.urls import path 
from . import views

app_name='profile'
urlpatterns = [
	path('login/', views.user_login, name='login'),
	path('', views.profile, name='profile'),
	path('edit/', views.edit, name='edit'),
	path('favorites/', views.list_favorites, name='favorites'),
	path('add_fav/', views.add_to_favorities, name='add_fav'),
	path('admin/contacts/<int:email_id>/', views.admin_email_detail, name='admin_email_detail'),

]

profiles/models.py
from django.db import models
from django.conf import settings 
from property.models import Property


# Create your models here.

class Profile(models.Model):
	user          = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='profile', on_delete=models.CASCADE)
	date_of_birth = models.DateField(blank=True, null=True)
	mobile	      = models.CharField(max_length=20)
	photo	      = models.ImageField(upload_to="users/%Y/%m/%d/", blank=True)
	about 		  = models.TextField(blank=True)
	my_favorities = models.ManyToManyField(Property, related_name='user_liked', blank=True)

	# def __str__(self):
	# 	return f'Profile for user {self.user.username}'

class Team(Profile):
	priority   = models.IntegerField()
	occupation = models.CharField(max_length=30)
	created_at = models.DateField(auto_now_add=True)
	update_at  = models.DateField(auto_now=True)

	# def __str__(self):
	# 	return self.user

	class Meta:
		ordering = ['-created_at']
		verbose_name_plural = 'Team Members'



# class MyFavorites(models.Model):
# 	user         = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
# 	appartment   = models.ForeignKey(Property, on_delete=models.CASCADE, blank=True, null=True)
# 	created_at   = models.DateTimeField(auto_now_add=True)
# 	updated_at   = models.DateTimeField(auto_now=True)


	# def __str__(self):
	# 	return self.user.username

profiles/forms.py
from django import forms 
from .models import Profile
from django.contrib.auth.models import User 

class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
	password  = forms.CharField(label='Password', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

	class Meta:
		model = User
		fields= ('username', 'first_name', 'email')

	def clean_password2(self):
		cd = self.cleaned_data
		if cd['password'] != cd['password2']:
			raise forms.ValidationError('Passwords don\'t match.')
		return cd['password2']	


class UserEditForm(forms.ModelForm):
	class Meta:
		model  = User
		fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
	class Meta:
		model  = Profile 
		fields = ('date_of_birth', 'mobile', 'photo', 'about')

	

castle/views.py
from django.shortcuts import render
from django.core.mail import BadHeaderError, send_mail
from django.http      import HttpResponse, HttpResponseRedirect
from additions.models import FAQ
from rentals.models   import Properties
from profiles.models  import Team 
from contacts.models  import Emails
from django.contrib.auth.models import User
from django.views.decorators.cache import cache_page
from django.views.decorators.vary  import vary_on_cookie
# from django.templates import RequestContext

@vary_on_cookie
@cache_page(60)
def home(request):
	hauses     = Properties.objects.all()[9:]
	print(hauses)
	teams    = User.objects.filter(is_active=True, is_staff=True)[3:] 
	featured = Properties.objects.filter(featured=True)[10:]
	
	return render(request, 'home/index.html',{
		'hauses':hauses,
		'teams':teams,
		'featured':featured})

@vary_on_cookie
@cache_page(3600)
def contacts(request):
	return render(request, 'contacts/contact.html',{})

@vary_on_cookie
@cache_page(3600)
def faq(request):
	faq = FAQ.objects.filter(is_active=True)
	# faq = FAQ.objects.all()
	return render(request, 'faq/faq.html', {'faq':faq})


def error_404(request):
	return render(request, 'errors/404.html')

def handler404(request, exception):
	return render(request, '404.html', {})

def handler500(request, *args, **kwargs):
	return render(request, '500.html', {})


def send_mail(request):
	subject = request.POST.get('subject','')
	message = request.POST.get('message', '')
	from_email= request.POST.get("from_email","")
	if subject and message and from_email:
		try:
			print('email has been sent successfully')
			send_mail(subject, message, from_email, ['admin@example.com'])
		except:
			return HttpResponse('Invalid header found.')
		return HttpResponseRedirect('/contact/thanks/')
	else:
		return HttpResponse('Make sure all fields are entered and valid.')	

			

profiles/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse, Http404
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth import authenticate, login, get_user_model 
from django.contrib.auth.models import User
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_GET

from common.decorators import ajax_required

from contacts.forms import AgentForm, ReplyForm
from .forms import LoginForm, UserEditForm, ProfileEditForm

# from .models import MyFavorites
from .models import Profile, Team
from contacts.models import EmailToAgent
from property.models import Property 
from profiles.models import Team


# Create your views here.

def user_login(request):
	if request.method == "POST":
		form     = LoginForm(request.POST)
		if form.is_valid():
			cd   = form.cleaned_data
			user = authenticate(request, username=cd['username'], password=cd['password'])
			if user is not None:
				if user.is_active:
					login(request, user)
					return HttpResponse('Authenticated Successfully')
				else:
					return HttpResponse('Disabled account')
		else:
			return HttpResponse('Invalid Login')
	else:
		form  = LoginForm()
	return render(request, 'profile/login.html', {'form':form})	


def register(request):
	if request.method == 'POST':
		form  = UserRegistrationForm(request.POST)
		print('validating the user')
		if form.is_valid():
			new_user = form.save(commit=False)
			new_user.set_password(form.cleaned_data['password'])
			print('saving user into database')
			new_user.save()
			Profile.objects.create(user=new_user)
			return render(request, 'profile/profile.html', {'new_user':new_user})
		else:
			# print(form.errors)
			pass	
	else:
		form  = UserRegistrationForm()
	return render(request, 'registration/register.html', {'user_form':form})



@login_required
def profile(request):
	try:
		profile = Profile.objects.get(user=request.user)
	except Profile.DoesNotExist:
		profile = Profile.objects.create(user=request.user)
		messages.info(request, 'You have not filled your account data!')

	return render(request, 'profile/profile.html', {'profile':profile})

@login_required
# @require_POST
def edit(request):
	if request.method =="POST":
		user_form     = UserEditForm(instance=request.user, data=request.POST)
		profile_form  = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()
			messages.success(request, 'Your profile updated successfully!')
		else:
			messages.error(request, 'Error updating your profile')	

		# image = Profile.objects.get(user=request.user).photo
		image = get_object_or_404(Profile, user=request.user).photo
			
	else:
		user_form     = UserEditForm(instance=request.user)
		profile_form  = ProfileEditForm(instance=request.user.profile)
		
		image = get_object_or_404(Profile, user=request.user).photo		
		
	return render(request, 'profile/edit.html',
					{'user':user_form,
					 'profile':profile_form, 'image':image})	 
	

@login_required
def list_favorites(request):
	# fav_list = MyFavorites.objects.filter(user=request.user)
	# properties = Property.objects.filter()
	profile =  Profile.objects.filter(user=request.user).first()
	return render(request, 'profile/list_favorites.html', {'profile':profile})


@ajax_required
@login_required
@require_POST
def add_to_favorities(request):
	app_id = request.POST.get('id')
	action = request.POST.get('action')
	if app_id and action:
		try:
			user = Profile.objects.get(user=request.user)
			if action =="like":
				user.my_favorities.add(app_id)
			else:
				user.my_favorities.remove(app_id)
			return JsonResponse({'status':'ok'})

		except:
			pass
	return JsonResponse({'status':'error'})		

def is_ajax(request):
	return request.META.get("HTTP_X_REQUESTED_WITH") == "XMLHttpRequest"


def list_agents(request):
	agents  = get_user_model().objects.filter(is_active=True, is_staff=True).exclude(is_superuser=True)
	# agents = Team.objects.all()
	return render(request, 'agent/agent_list.html', {"agents":agents})

# @require_GET
def detail_agent(request, id):
	User  = get_user_model()
	agent = get_object_or_404(User, id=id, is_active=True)
	all_properties = Property.objects.filter(id=agent.id).order_by('-created')
	paginator  = Paginator(all_properties, per_page=10)
	page_num = int(request.GET.get('page', 1))
	if page_num>paginator.num_pages:
		raise Http404
	properties = paginator.page(page_num) 

	if is_ajax(request):
		return render(request, 'agent/_properties.html', {'properties':properties})	
	agent_id = agent.id
	if request.method=='POST':
		form = AgentForm(request.POST, initial={'agent':agent_id})
		print('post request recieved')
		if form.is_valid():
			form.save()
	else:
		
		form = AgentForm(initial={'agent':agent_id})		
	return render(request, 'agent/agent_profile.html', 
		{
		'agent':agent, 
		'properties':all_properties,
		'form':form
		})	

@staff_member_required
def admin_email_detail(request, email_id):
	email = get_object_or_404(EmailToAgent, id=email_id)
	agent = get_object_or_404(Team, id=email.agent.id)
	sender= email.agent.first_name + email.agent.last_name
	recipent = email.email
	if request.method =='POST':
		form = ReplyForm(request.POST)
		if form.is_valid():
			form.save()
	else:
		form = ReplyForm(initial={'agent':agent.id, 'sender':sender, 'sender':recipent})	
	return render(request, 'admin/contacts/emailtoagent/detail.html', {'email':email, 'form':form})

templates/castle/profile/edit.html
{% extends 'base.html' %}
{% load static %}
{%load i18n %}
{% block page_title %}
  <title>
    {% trans "Edit Profile" %}: {{request.user.username}}
  </title>
{% endblock %}
{% block content %}
  
  <!-- Profile Start -->
  <section id="agent-2-peperty" class="profile padding">

    {% include 'profile/profile-menu.html' %}
      
    <div class="container-3" style="padding-top: 20px;">
    <h1 class="page-header">Edit Profile</h1>
    <div class="row">
      <!-- left column -->
    <form class="form-horizontal" method="POST" enctype="multipart/form-data">

      <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="text-center">
          <img src="{% if image %}{{image.url}}{% else %}{% static 'images/profile_photo.jpg' %}{% endif %}" class="avatar img-circle img-thumbnail" alt="">
          <h6><input type="checkbox" name="photo" id="id_photo"> <label for="id_photo"> Clear</label></h6>
          <input type="file" name="photo" accept="image/*" id="id_photo" class="text-center center-block well-sm">
        </div>
      </div>
      <!-- edit form column -->
      <div class="col-md-8 col-sm-6 col-xs-12 personal-info">
        
        {% if messages %}
          <ul class="messages">
            {% for message in messages %}
              <li class="{{ message.tags }}">
              <div class="alert alert-{% if message.tags == 'error'%}danger{% else %}{{message.tags}} {% endif %}  alert-dismissable">
                <a class="panel-close close" data-dismiss="alert">×</a> 
                <i class="fa fa-coffee"></i>
                {{ message|safe }}
              </div>
              </li>
            {% endfor %}
          </ul>
      {% endif %}
    
      
        <h3>Personal info</h3>
          
          <div class="form-group">
            {{ user.first_name.errors }}
            <label class="col-lg-3 control-label">First name:</label>
            <div class="col-lg-8">
              <input class="form-control" value="{{user.first_name.value}}" name="first_name">
            </div>
          </div>
         
          <div class="form-group">
            {{ user.last_name.errors }}
            <label class="col-lg-3 control-label">Last name:</label>
            <div class="col-lg-8">
              <input class="form-control" value="{{user.last_name.value}}" name="last_name">
            </div>
          </div>

          <div class="form-group">
            {{ profile.mobile.errors }}
            <label class="col-lg-3 control-label">Phone:</label>
            <div class="col-lg-8">
              <input class="form-control" value="{{profile.mobile.value}}" name="mobile">
            </div>
          </div>

          <div class="form-group">
            {{ user.email.errors }}
            <label class="col-lg-3 control-label">Email:</label>
            <div class="col-lg-8">
              <input class="form-control" value="{{user.email.value}}" name="email">
            </div>
          </div>

          <div class="form-group">
            {{ profile.date_of_birth.errors }}
            <label class="col-lg-3 control-label">Date of birth:</label>
            <div class="col-lg-8">
              <input class="form-control" type="date" value="{{profile.date_of_birth.value|date:"yy-m-d"}}" name="date_of_birth">
            </div>
          </div>

          <div class="form-group">
            {{ profile.about.errors }}
            <label class="col-lg-3 control-label">About yourself:</label>
            <div class="col-lg-8">
              <textarea class="form-control" name="about"> {{profile.about.value}}</textarea>
            </div>
          </div>

          {% csrf_token %}
          
          <div class="form-group">
            <label class="col-md-3 control-label"></label>
            <div class="col-md-8">
              <input class="btn btn-primary" value="Save Changes" type="submit">
              <span></span>
              <input class="btn btn-default" value="Cancel" type="reset">
            </div>
          </div>

      </div>
    </div>
  </form>
  </div>

  </section>
  <!-- Profile end -->

{% endblock %}

templates/castle/profile/list_favorites.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block page_title %}
  <title>
    {% trans "Favorites of " %} {{request.user.username}}
  </title>
{% endblock %}
{% block content %}

<!-- Favorite Properties  -->
<section id="property" class="padding_top listing1">
   {% include 'profile/profile-menu.html' %}
</section>
<!-- Favorite Properties End -->

{% endblock %}

{% block domready %}
<script type="text/javascript">
  $('a.like').click(function(e){
    e.preventDefault();
    var link = $(this)
    console.log(link.data('action'))
    $.post('{% url "profile:add_fav" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action')
      },

      function(data){
        console.log(data)
        if (data['status'] == 'ok')
        {
          var previous_action = link.data('action');
          // toggle data-action
          link.data('action', previous_action == 'like' ?
          'unlike' : 'like');
          // toggle link text
          link.html(previous_action == 'like' ? '<span class="glyphicon glyphicon-heart" aria-hidden="true" wfd-id="4817"></span>' :
          '<span class="glyphicon glyphicon-heart-empty" aria-hidden="true" wfd-id="4817"></span>');
        }
      }
    );
    });
</script>
{% endblock %}

templates/castle/profile/profile-menu.html
   <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="f-p-links margin_bottom">
            <li><a href="{% url "profile:profile" %}" class="active"><i class="icon-icons230"></i>Profile</a></li>
            <li><a href="{% url "profile:favorites" %}"><i class="icon-icons215"></i> My Properties(UD)</a></li>
            <li><a href="{% url "profile:favorites" %}"><i class="icon-icons215"></i> Submit Property(UD)</a></li>
            <li><a href="{% url "profile:favorites" %}"><i class="icon-icons43"></i> Favorite Properties</a></li>
            <li><a href="{% url 'account_logout' %}"><i class="icon-lock-open3"></i>Logout</a></li>
          </ul>
        </div>
      </div>
    </div>

templates/castle/profile/profile.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block page_title %}
  <title>
    {% trans "Profile" %}: {{request.user.username}}
  </title>
{% endblock %}
{% block content %}


     {% if messages %}
          <ul class="messages">
            {% for message in messages %}
              <li class="{{ message.tags }}">
              <div class="alert alert-{% if message.tags == 'error'%}danger{% else %}{{message.tags}} {% endif %}  alert-dismissable">
                <a class="panel-close close" data-dismiss="alert">×</a> 
                <i class="fa fa-coffee"></i>
                {{ message|safe }}
              </div>
              </li>
            {% endfor %}
          </ul>
      {% endif %}
  

  <!-- Profile Start -->
  <section id="agent-2-peperty" class="profile padding">

    {% include 'profile/profile-menu.html' %}
    

    <div class="container-3">
     <div class="mainbody container-fluid">
    <div class="row">
        <div style="padding-top:20px;"> </div>
        <div class="col-lg-3 col-md-3 hidden-sm hidden-xs">
            <div class="panel panel-default">

              {% with user=profile.user %}
                <div class="panel-body">
                    <div class="media">
                        <div align="center">
                            <img class="thumbnail img-responsive" src="
                            {% if profile.photo %}{{profile.photo.url}}{% else %} {% static 'images/profile_photo.jpg' %}{% endif %}" width="300px" height="300px">
                        </div>
                        <div class="media-body">
                            <hr>
                            <h5><strong>Profile</strong></h5>
                            <p>{{user.username}}</p>
                            <hr>
                            <h5><strong>Date of Birth</strong></h5>
                            <p>{{profile.date_of_birth}}</p>
                        </div>
                    </div>
                </div>
                {% endwith %}
            </div>
        </div>
        <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <span>
                        <h1 class="panel-title pull-left" style="font-size:30px;">{{user.first_name|capfirst}} {{user.last_name}}<small> {{user.email}}</small> <i class="fa fa-check text-success" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="{{user.first_name}} is sharing with you"></i></h1>
                        <div class="dropdown pull-right">
                            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                <i class="fa fa-cog" aria-hidden="true"></i> 
                                 <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <li><a href="{% url 'profile:edit' %}">Edit Profile</a></li>
                                <li><a href="#">Change Password</a></li>
                            </ul>
                        </div>
                    </span>
                    <br><br>
                    <i class="fa fa-tags" aria-hidden="true"></i> {{profile.mobile}}
                    <br><br><hr>
                    
                    <div class="post-content" wfd-id="76">
                        {{profile.about}}
                    </div>
                    <hr>
                    <span class="pull-left">
                        <a href="{% url 'profile:favorites' %}" class="btn btn-link" style="text-decoration:none;"><i class="fa fa-fw fa-heart" aria-hidden="true"></i> Favorities <span class="badge">{{profile.my_favorities.count}}</span></a>
                    </span>


                    <span class="pull-right">
                        <a href="#" class="btn btn-link" style="text-decoration:none;"><i class="fa fa-lg fa-at" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="Mention"></i></a>
                        <a href="#" class="btn btn-link" style="text-decoration:none;"><i class="fa fa-lg fa-envelope-o" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="Message"></i></a>
                        <a href="#" class="btn btn-link" style="text-decoration:none;"><i class="fa fa-lg fa-ban" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="Ignore"></i></a>
                    </span>
                </div>
            </div>
            <hr>

        </div>
    </div>
</div>
    </div>

  </section>
  <!-- Profile end -->

{% endblock %}

templates/castle/profile/property_detail1.html
{% extends 'base.html' %}
{% block content %}
  

    {% if messages %}
      <ul class="messages">
      {% for message in messages %}
        <li class="{{ message.tags }}">
          <div class="alert alert-{% if message.tags == 'error'%}danger{% else %}{{message.tags}} {% endif %}" role="alert">
            {{ message|safe }}
            <button type="button" class="close" data-dismiss="modal" aria-label="Close" wfd-id="1025">
          <span aria-hidden="true">×</span>
        </button>
          </div>
        </li>
      {% endfor %}
      </ul>
    {% endif %}
  

  <!-- Profile Start -->
  <section id="agent-2-peperty" class="profile padding">

    {% include 'profile/profile-menu.html' %}
    
    <div class="container-3">
      <div class="row">
        <div class="col-md-4 col-sm-6 col-xs-12">
          <h2 class="text-uppercase bottom30">my profile</h2>
          <div class="agent-p-img">
            <img src="images/profile.jpg" class="img-responsive" alt="image"/>
            <a href="#" class="top10 bottom20">Update Profile Picture</a>
            <p class="text-center">Minimum 215px x 215px<span>*</span></p>
          </div>
        </div>
        <div class="col-md-8">
          <div class="profile-form">
            <div class="row">
              
              <form class="form-horizontal" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{user_form.as_p}}
                {{profile_form.as_p}}
                <p><input type="submit" value="Save changes"></p> 
              </form>
             
            </div>
          </div>
        </div>
      </div>
    </div>

  </section>
  <!-- Profile end -->




<div class="container">
<div class="row">
<div class="col-md-10 ">
<form class="form-horizontal">
<fieldset>

<!-- Form Name -->
<legend>User profile form requirement</legend>

<!-- Text input-->


<div class="form-group">
  <label class="col-md-4 control-label" for="First Name">First Name</label>  
  <div class="col-md-4">
   <div class="input-group">
     <div class="input-group-addon">
      <i class="fa fa-user">
      </i>
     </div>
     <input id="First Name" name="first_name" type="text" placeholder="First Name" id='id_first_name' class="form-control input-md">
    </div>
  </div>
</div>

<div class="form-group">
  <label class="col-md-4 control-label" for="Last Name">Last Name</label>  
  <div class="col-md-4">
   <div class="input-group">
     <div class="input-group-addon">
      <i class="fa fa-user">
      </i>
     </div>
     <input id="Last Name" name="last_name" type="text" placeholder="Last Name" id='id_last_name' class="form-control input-md">
    </div>
  </div>
</div>

<div class="form-group">
  <label class="col-md-4 control-label" for="Phone Number">Phone Number</label>  
  <div class="col-md-4">
   <div class="input-group">
     <div class="input-group-addon">
      <i class="fa fa-user">
      </i>
     </div>
     <input id="mobile" name="mobile" type="text" placeholder="Mobile" id='id_mobile' class="form-control input-md">
    </div>
  </div>
</div>

<!-- File Button --> 
<div class="form-group">
  <label class="col-md-4 control-label" for="Upload photo">Upload photo</label>
  <div class="col-md-4">
    <input id="Upload photo" name="Upload photo" class="input-file" type="file">
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="Date Of Birth">Date Of Birth</label>  
  <div class="col-md-4">
  <div class="input-group">
       <div class="input-group-addon">
         <i class="fa fa-birthday-cake"></i>
       </div>
       <input id="Date Of Birth" name="date_of_birth" type="text" placeholder="Date Of Birth" class="form-control input-md">
      </div>
  </div>
</div>




<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="Email Address">Email Address</label>  
  <div class="col-md-4">
  <div class="input-group">
       <div class="input-group-addon">
     <i class="fa fa-envelope-o"></i>
        
       </div>
    <input id="Email Address" name="Email Address" type="text" placeholder="Email Address" class="form-control input-md">
    
      </div>
  
  </div>
</div>













<!-- Textarea -->
<div class="form-group">
  <label class="col-md-4 control-label" for="Overview (max 200 words)">Overview (max 200 words)</label>
  <div class="col-md-4">                     
    <textarea class="form-control" rows="10"  id="id_about" name="about">Overview</textarea>
  </div>
</div>


<div class="form-group">
  <label class="col-md-4 control-label" ></label>  
  <div class="col-md-4">
  <a href="#" class="btn btn-success"><span class="glyphicon glyphicon-thumbs-up"></span> Submit</a>
  <a href="#" class="btn btn-danger" value=""><span class="glyphicon glyphicon-remove-sign"></span> Clear</a>
    
  </div>
</div>

</fieldset>
</form>
</div>
<div class="col-md-2 hidden-xs">
<img src="http://websamplenow.com/30/userprofile/images/avatar.jpg" class="img-responsive img-thumbnail ">
  </div>


</div>
   </div>
  
{% endblock %}